"""empty message

Revision ID: ed6c9d29381d
Revises: 
Create Date: 2023-11-27 15:07:11.231745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6c9d29381d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('opportunities')
    op.drop_table('registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('registration_date', sa.DATETIME(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('opportunity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_registrations_account_id_accounts'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name='fk_registrations_opportunity_id_opportunities'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
